### ISSUE TITLE
Fix: Implement way to verify device keys if they have changed or not

### ISSUE THREAD

**Issue by Fatima-Habboub** [Rezivure/grid-frontend#11]

**Comment by chandlergach** [comment]
Created UserDeviceKeys table in local db to track users Device IDs and Identity Keys. If they change it will notify the user over the contact's avatar. Does not stop sharing of locations...to be implemented in future Security Preferences.

Device IDs and keys are updated currently on fetch/updating locations. In the future can be done on updating others.
